// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVAT_aB9AzkPJ-B9K0FmVWm8gs3aafKzo',
    appId: '1:716326662088:web:212b51f3adab71c9219afd',
    messagingSenderId: '716326662088',
    projectId: 'testing-projek-8349e',
    authDomain: 'testing-projek-8349e.firebaseapp.com',
    databaseURL: 'https://testing-projek-8349e-default-rtdb.firebaseio.com',
    storageBucket: 'testing-projek-8349e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnh0H7fAdB8FU6mtcRbYUBnkyla6e1nEc',
    appId: '1:716326662088:android:fdd97f4403296dd0219afd',
    messagingSenderId: '716326662088',
    projectId: 'testing-projek-8349e',
    databaseURL: 'https://testing-projek-8349e-default-rtdb.firebaseio.com',
    storageBucket: 'testing-projek-8349e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUP9R6qKEv2fZfEtuJ0Dc884m9uql7Hc',
    appId: '1:716326662088:ios:1fd1e493d4aa7c3a219afd',
    messagingSenderId: '716326662088',
    projectId: 'testing-projek-8349e',
    databaseURL: 'https://testing-projek-8349e-default-rtdb.firebaseio.com',
    storageBucket: 'testing-projek-8349e.appspot.com',
    iosClientId: '716326662088-ghahvqkpnqg3jcijn9tinehef8d7nb2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.risetKonsentrasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcUP9R6qKEv2fZfEtuJ0Dc884m9uql7Hc',
    appId: '1:716326662088:ios:1fd1e493d4aa7c3a219afd',
    messagingSenderId: '716326662088',
    projectId: 'testing-projek-8349e',
    databaseURL: 'https://testing-projek-8349e-default-rtdb.firebaseio.com',
    storageBucket: 'testing-projek-8349e.appspot.com',
    iosClientId: '716326662088-ghahvqkpnqg3jcijn9tinehef8d7nb2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.risetKonsentrasi',
  );
}
